#########################
# Discord Snowflake Ids #
#########################
# You can read about the TOML format at https://toml.io/en/.

status_messages = [
    "hiya :3",
    "leetcode ğŸ”¥",
    "sleeping ğŸ˜ª",
    "learning ğŸª¢",
    "coding âŒ¨ï¸"
]